### PR TITLE
Add NowSecure statistics link

### PR DESCRIPTION
**Pull request by keylowe**

### CODE REVIEW

**Comment by dweinstein** [comment]
👍  can also add https://www.nowsecure.com/blog/2016/12/29/enable-ios-app-transport-security-ats/ which precedes that one.

**Comment by keylowe** [comment]
@dweinstein that's the same link. I just changed the title to try and hook people with the stats.

**Comment by dweinstein** [comment]
sorry I edited my comment right after I realized I pasted the wrong URL.

**Comment by keylowe** [comment]
Nice!

**Pull request merged**
